[workspace]
members = [
    "netbench*",
]
exclude = [
    "netbench-cdk",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
incremental = false

[profile.bench]
lto = true
codegen-units = 1
incremental = false
debug = true
