[default]
binary = false
check-filename = true
[default.extend-identifiers]

[default.extend-words]

[files]
extend-exclude = [
    "request_response.json",
    "response.json",
    "bad_response.json",
    "cdk_config.json",
    "*.snap",
    "*.bin",
    "*.der",
    "*.ico",
    "*.pem",
]
